#!/usr/bin/env python
import re
import sys

MESSAGE_REGEX = re.compile(r"^#\d+\s(feat|fix|build|chore|ci|docs|style|refactor|perf|test):\s")

with open(sys.argv[1], "r") as f:
    message = f.read()

if not MESSAGE_REGEX.search(message):
    sys.exit(f"Invalid Commit Message: '{message}'")
