#!/usr/bin/env python
import re
import subprocess
import sys

with open(sys.argv[1], "r") as f:
    message = f.read()

output = subprocess.check_output(f"python check-commit-msg.py \"{message}\"")
print(output)