#!/usr/bin/env python
import re
import subprocess
import sys
from typing import Self


class Versions:
    __patch: int
    __minor: int
    __major: int

    def __init__(self, *, patch: int, minor: int, major: int):
        self.__patch = patch
        self.__minor = minor
        self.__major = major

    @property
    def patch(self) -> int:
        return self.__patch

    @property
    def minor(self) -> int:
        return self.__minor

    @property
    def major(self) -> int:
        return self.__major

    @patch.setter
    def patch(self, patch: int):
        self.__patch = patch

    @minor.setter
    def minor(self, minor: int):
        self.__minor = minor
        self.__patch = 0

    @major.setter
    def major(self, major: int):
        self.__major = major
        self.__minor = 0
        self.__patch = 0

    def __repr__(self):
        return f"v{self.__major}.{self.__minor}.{self.__patch}"

    @classmethod
    def from_version_str(cls, version_str: str) -> Self:
        version_list = version_str.removeprefix("v").split(".")

        patch = int(version_list[2])
        minor = int(version_list[1])
        major = int(version_list[0])

        return Versions(
            patch=patch,
            minor=minor,
            major=major
        )


current_branch = subprocess.check_output("git rev-parse --abbrev-ref HEAD").decode("utf-8").strip()

if current_branch != "main":
    sys.exit(0)

try:
    latest_tag = subprocess.check_output("git describe --tags --abbrev=0", stderr=subprocess.STDOUT).decode(
        "utf-8").strip()
    commits_since_tag = subprocess.check_output(f"git log {latest_tag}..HEAD --pretty=format:%s").decode("utf-8").split(
        "\n")
    versions = Versions.from_version_str(latest_tag)
except subprocess.CalledProcessError as e:
    if e.output.decode("utf-8").strip() != "fatal: No names found, cannot describe anything.":
        sys.exit(f"Error while getting tags {e}")

    commits_since_tag = subprocess.check_output(f"git log --pretty=format:%s").decode("utf-8").split("\n")
    versions = Versions(patch=0, minor=0, major=0)

for commit in commits_since_tag:
    split = re.split(r"#\d", commit, maxsplit=1)

    if len(split) == 1:
        continue

    commit_type = split[1].split(":")[0].strip()

    if re.search(r"(fix|chore|docs)", commit_type):
        # Patch
        versions.patch += 1
    elif re.search(f"(feat)", commit_type):
        # Minor
        versions.minor += 1
    elif re.search(r"(BREAKING_CHANGE)", commit_type):
        # Major
        versions.major += 1
    else:
        print(f"Invalid commit type {commit_type}")

subprocess.call(f"git tag {versions}")
subprocess.call(f"git push --tags")
