name: GitHub Actions
run-name: Test
on: [ push ]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
        env:
          AGENT_TOOLSDIRECTORY: /opt/github/actions-runner/_work/_tool

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pip install pytest
          pytest tests
          
